"""Generate assets/theme/futuremotion-fonts.css from the TTFs in app-reference/fonts.

Each font is converted to WOFF2 and embedded as a base64 data URL, so the exe
renders the fork's fonts without anything installed. Rerun this script after
changing FONTS or replacing a source file, then rebuild.

Requires: pip install fonttools brotli
"""
import base64
import io
from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "app-reference" / "fonts"
OUTPUT = ROOT / "assets" / "theme" / "futuremotion-fonts.css"

# (CSS family, font-style, font-weight, source file). A "min max" weight marks a
# variable font whose wght axis must cover that range; a single weight marks a
# static font whose OS/2 weight class must match it.
FONTS = [
    ("FM Inter", "normal", "400", "Inter Regular.ttf"),
    ("FM Inter", "italic", "400", "Inter Italic.ttf"),
    ("FM Inter", "normal", "600", "Inter SemiBold.ttf"),
    ("FM Inter", "italic", "600", "Inter SemiBold Italic.ttf"),
    ("FM JetBrains Mono", "normal", "100 800", "JetBrains Mono Regular.ttf"),
    ("FM JetBrains Mono", "italic", "100 800", "JetBrains Mono Italic.ttf"),
]


def check_weight(font: TTFont, weight: str, source: Path) -> None:
    bounds = [int(value) for value in weight.split()]
    if len(bounds) == 2:
        axes = {axis.axisTag: axis for axis in font["fvar"].axes} if "fvar" in font else {}
        if "wght" not in axes:
            raise SystemExit(f"{source.name}: declared variable weight {weight}, but the font has no wght axis")
        wght = axes["wght"]
        if wght.minValue > bounds[0] or wght.maxValue < bounds[1]:
            raise SystemExit(
                f"{source.name}: wght axis {wght.minValue:g}-{wght.maxValue:g} does not cover {weight}"
            )
    elif font["OS/2"].usWeightClass != bounds[0]:
        raise SystemExit(
            f"{source.name}: OS/2 weight class is {font['OS/2'].usWeightClass}, declared {weight}"
        )


def font_face(family: str, style: str, weight: str, source: Path) -> str:
    # recalcTimestamp=False keeps the output byte-identical across runs.
    font = TTFont(source, recalcTimestamp=False)
    check_weight(font, weight, source)
    font.flavor = "woff2"
    buffer = io.BytesIO()
    font.save(buffer)
    data = base64.b64encode(buffer.getvalue()).decode("ascii")
    return (
        f'@font-face{{font-family:"{family}";font-style:{style};font-weight:{weight};'
        f'font-display:block;src:url(data:font/woff2;base64,{data}) format("woff2")}}'
    )


def main() -> None:
    faces = []
    for family, style, weight, filename in FONTS:
        source = SOURCE_DIR / filename
        if not source.is_file():
            raise SystemExit(f"missing source font: {source}")
        faces.append(font_face(family, style, weight, source))
        print(f"{family} {style} {weight} <- {filename}")

    header = (
        "/* Generated by scripts/build-theme-fonts.py from app-reference/fonts. Do not edit by hand.\n"
        "   Fonts: Inter and JetBrains Mono, SIL Open Font License 1.1 (see assets/theme/FONTS-LICENSE.md). */\n"
    )
    OUTPUT.write_text(header + "\n".join(faces) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
